public class AccountHandler{
    
    public static void insertAccount(Integer value){
        
       Integer counter=1;
       List<Account>addAccounts = new List<Account>();
        
        while(counter<=value){
            System.debug('Counter Value before Incrementing ' + counter);
            
            Account store= new Account();
            
            store.Name= 'Acme Inc n' +counter;
            store.AccountNumber= 'A000n'+ counter;
            addAccounts.add(store);
            
            System.debug(addAccounts);
            
            counter = counter + 1;
            System.debug('Counter Value after incrementing ' + counter);
            
        }
        
        
        System.debug('Size of Account List: ' + addAccounts.size() );
        System.debug('Elements in Account List: ' + addAccounts);
        
        
        insert addAccounts;
        
        
    }

}